export const mockedChats: Chat[] = [
    {
        id: '1',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'John Doe',
        lastMessage: {
            isSendByUser: true,
            sent: new Date(),
            text: 'Hello, how are you?',
            isRead: true,
        },
    },
    {
        id: '2',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Alice Smith',
        lastMessage: {
            isSendByUser: false,
            sent: new Date(),
            text: "I'm doing well, thanks!",
            isRead: true,
        },
    },
    {
        id: '3',
        isSelected: true,
        unreadNumber: 0,
        companionName: 'Bob Johnson',
        lastMessage: {
            isSendByUser: false,
            sent: new Date(),
            text: "What's up?",
            isRead: false,
        },
    },
    {
        id: '4',
        isSelected: false,
        unreadNumber: 3,
        companionName: 'Eve Anderson',
        lastMessage: {
            isSendByUser: false,
            sent: new Date(),
            text: "How's your day going?",
            isRead: false,
        },
    },
    {
        id: '5',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Charlie Brown',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'I had a great day!',
            isRead: true,
        },
    },
    {
        id: '6',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Grace Davis',
        lastMessage: {
            isSendByUser: false,
            sent: new Date(),
            text: "Let's meet up tomorrow.",
            isRead: true,
        },
    },
    {
        id: '7',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'Oliver Lee',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'Sure, where should we meet?',
            isRead: false,
        },
    },
    {
        id: '8',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'Emma White',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'How about the coffee shop on Main Street? Sounds good. See you there!',
            isRead: true,
        },
    },
    {
        id: '1',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'John Doe',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'Hello, how are you?',
            isRead: true,
        },
    },
    {
        id: '2',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Alice Smith',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: "I'm doing well, thanks!",
            isRead: true,
        },
    },
    {
        id: '3',
        isSelected: false,
        unreadNumber: 1,
        companionName: 'Bob Johnson',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: "What's up?",
            isRead: false,
        },
    },
    {
        id: '4',
        isSelected: false,
        unreadNumber: 3,
        companionName: 'Eve Anderson',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: "How's your day going?",
            isRead: false,
        },
    },
    {
        id: '5',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Charlie Brown',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'I had a great day!',
            isRead: true,
        },
    },
    {
        id: '6',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Grace Davis',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: "Let's meet up tomorrow.",
            isRead: true,
        },
    },
    {
        id: '7',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'Oliver Lee',
        lastMessage: {
            isSendByUser: false,
            sent: new Date(),
            text: 'Sure, where should we meet?',
            isRead: false,
        },
    },
    {
        id: '8',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'Emma White',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'How about the coffee shop on Main Street? Sounds good. See you there!',
            isRead: true,
        },
    },
    {
        id: '1',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'John Doe',
        lastMessage: {
            sent: new Date(),
            text: 'Hello, how are you?',
            isSendByUser: false,
            isRead: true,
        },
    },
    {
        id: '2',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Alice Smith',
        lastMessage: {
            sent: new Date(),
            text: "I'm doing well, thanks!",
            isSendByUser: false,
            isRead: true,
        },
    },
    {
        id: '3',
        isSelected: false,
        unreadNumber: 1,
        companionName: 'Bob Johnson',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: "What's up?",
            isRead: false,
        },
    },
    {
        id: '4',
        isSelected: false,
        unreadNumber: 3,
        companionName: 'Eve Anderson',
        lastMessage: {
            sent: new Date(),
            text: "How's your day going?",
            isSendByUser: false,
            isRead: false,
        },
    },
    {
        id: '5',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Charlie Brown',
        lastMessage: {
            sent: new Date(),
            text: 'I had a great day!',
            isSendByUser: false,
            isRead: true,
        },
    },
    {
        id: '6',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Grace Davis',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: "Let's meet up tomorrow.",
            isRead: true,
        },
    },
    {
        id: '7',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'Oliver Lee',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'Sure, where should we meet?',
            isRead: false,
        },
    },
    {
        id: '8',
        isSelected: false,
        unreadNumber: 2,
        companionName: 'Emma White',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'How about the coffee shop on Main Street? Sounds good. See you there!',
            isRead: true,
        },
    },
    {
        id: '9',
        isSelected: false,
        unreadNumber: 1,
        companionName: 'Liam Harris',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'Sounds good. See you there!',
            isRead: false,
        },
    },
    {
        id: '10',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Ava Martin',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'How about the coffee shop on Main Street? Great! Looking forward to it.',
            isRead: true,
        },
    },
    {
        id: '11',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Sarah Wilson',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'I had a long day at work today.',
            isRead: false,
        },
    },
    {
        id: '12',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Michael Jones',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'I can imagine. Tell me about it.',
            isRead: true,
        },
    },
    {
        id: '13',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Emily Davis',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'I had back-to-back meetings.',
            isRead: false,
        },
    },
    {
        id: '14',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Daniel Smith',
        lastMessage: {
            sent: new Date(),
            isSendByUser: false,
            text: 'That sounds exhausting!',
            isRead: true,
        },
    },
    {
        id: '15',
        isSelected: false,
        unreadNumber: 0,
        companionName: 'Olivia Johnson',
        lastMessage: {
            sent: new Date(),
            text: 'Yes, it was. I need a break.',
            isSendByUser: false,
            isRead: false,
        },
    },
];
export const chatHistory: Message[] = [
    {
        text: 'Привіт! Як ти сьогодні?',
        isSendByUser: false,
        isRead: true,
        sent: new Date('2023-09-01T10:00:00'),
    },
    {
        text: 'Привіт! Я чудово, дякую!',
        isSendByUser: true,
        isRead: true,
        sent: new Date('2023-09-01T10:05:00'),
    },
    {
        text: 'Що нового?',
        isSendByUser: false,
        isRead: true,
        sent: new Date('2023-09-01T10:10:00'),
    },
    {
        text: 'Нічого особливого, просто працюю.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:15:00'),
    },
    {
        text: 'Я теж сьогодні працюю. Який у тебе план на вечір?',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:20:00'),
    },
    {
        text: 'Планів немає, можливо подивлюся фільм.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:25:00'),
    },
    {
        text: 'Це гарна ідея! Що за фільм ти хочеш подивитися?',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:30:00'),
    },
    {
        text: 'Думаю, подивлюся нову комедію, яку всі рекомендують.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:35:00'),
    },
    {
        text: 'Слухай, а як у тебе справи на роботі?',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:40:00'),
    },
    {
        text: 'На роботі все добре, нічого нового.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:45:00'),
    },
    {
        text: 'Чудово! Бажаю вдалого перегляду фільму!',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:50:00'),
    },
    {
        text: 'Дякую! Згодом поговоримо.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:55:00'),
    },
    {
        text: 'Окей, пиши, якщо щось цікаве трапиться!',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T11:00:00'),
    },
    {
        text: "Обов'язково! До зустрічі!",
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T11:05:00'),
    },
    {
        text: 'До зустрічі! :)',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T11:10:00'),
    },
    {
        text: 'Здоровенькі були! :)',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T11:15:00'),
    },
    {
        text: 'Привіт! Як ти сьогодні?',
        isSendByUser: false,
        isRead: true,
        sent: new Date('2023-09-01T10:00:00'),
    },
    {
        text: 'Привіт! Я чудово, дякую!',
        isSendByUser: true,
        isRead: true,
        sent: new Date('2023-09-01T10:05:00'),
    },
    {
        text: 'Що нового?',
        isSendByUser: false,
        isRead: true,
        sent: new Date('2023-09-01T10:10:00'),
    },
    {
        text: 'Нічого особливого, просто працюю.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:15:00'),
    },
    {
        text: 'Я теж сьогодні працюю. Який у тебе план на вечір?',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:20:00'),
    },
    {
        text: 'Планів немає, можливо подивлюся фільм.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:25:00'),
    },
    {
        text: 'Це гарна ідея! Що за фільм ти хочеш подивитися?',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:30:00'),
    },
    {
        text: 'Думаю, подивлюся нову комедію, яку всі рекомендують.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:35:00'),
    },
    {
        text: 'Слухай, а як у тебе справи на роботі?',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:40:00'),
    },
    {
        text: 'На роботі все добре, нічого нового.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:45:00'),
    },
    {
        text: 'Чудово! Бажаю вдалого перегляду фільму!',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T10:50:00'),
    },
    {
        text: 'Дякую! Згодом поговоримо.',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T10:55:00'),
    },
    {
        text: 'Окей, пиши, якщо щось цікаве трапиться!',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T11:00:00'),
    },
    {
        text: "Обов'язково! До зустрічі!",
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T11:05:00'),
    },
    {
        text: 'До зустрічі! :)',
        isSendByUser: false,
        isRead: false,
        sent: new Date('2023-09-01T11:10:00'),
    },
    {
        text: 'Здоровенькі були! :)',
        isSendByUser: true,
        isRead: false,
        sent: new Date('2023-09-01T11:15:00'),
    },
].reverse();
export interface Chat {
    id: string;
    unreadNumber: number;
    companionName: string;
    lastMessage: Message;
    isSelected: boolean;
}
export interface Message {
    isSendByUser: boolean;
    sent: Date;
    text: string;
    isRead: boolean;
}

export const defaultChat = {
    userName: 'Bob Johnson',
    isOnline: true,
    lastSeen: new Date(),
};
